# Generated by Django 5.0.3 on 2024-03-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='myText',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
    ]
